### ISSUE TITLE
Quotes Downloader - Limitless Synchronization 'attempt'

### ISSUE THREAD

**Issue by drayzen** [SoftFx/FdkUtilities#4]
In Quotes Downloader, can you add either a command line switch or interface option to limit the number of 'attempt' for a failed access?
It currently keeps trying the same location endlessly.

**Comment by SoftFx** [comment]
![quotesdownloader](https://user-images.githubusercontent.com/12148357/38490643-4b98566c-3bf2-11e8-8816-d0991b42bbc0.png)

Fixed

**Comment by drayzen** [comment]
Thanks for that.  ;)
Ideally the broker would have their data working so this wouldn't be needed to work around the errors, but at least a solution in the interim.

**Comment by drayzen** [comment]
Has something possibly reverted in the build? I'm not seeing the 'Retries' option any more.
Does it matter if the VC Redist. install is the x64 or x32? (x64 currently installed, prefer not to downgrade to x32)
(Win10 1803)

Can these errors in the data be corrected?
If yes, should I report timestamps to you guys or the Broker? (Though I expect broker wouldn't be bothered to actually do anything about it...)  :\
